imports:
    - { resource: %kernel.root_dir%/config/defaults/parameters.application.defaults.yml }
    - { resource: %kernel.root_dir%/config/defaults/environment.application.defaults.yml }
    - { resource: "@NetgustoBootCampBundle/Resources/config/preprocessors/environment_resolver.php" }
    - { resource: "@NetgustoBootCampBundle/Resources/config/preprocessors/database_loader.php" }