imports:
    - { resource: "@NetgustoBootCampBundle/Resources/config/preprocessors/environment_resolver.php" }
    - { resource: "@NetgustoBootCampBundle/Resources/config/preprocessors/database_loader.php" }