parameters:
    appversion: 1.0.0

services:

    bootcamp.autoroute:
        class: Netgusto\AutorouteBundle\Routing\AutorouteProvider
        arguments:
            - "%kernel.root_dir%/src/Netgusto/CoreBundle/Resources/config/routes/init.yml"
        tags:
            - { name: autoroute.provider }

    bootcamp.systemhealth:
        class: Netgusto\BootCampBundle\EventListener\SystemHealthCheckerListener
        arguments:
            # Event listener are not lazyloaded, so need to inject service container to still lazyload @system.status
            - @service_container
            - @environment
            - @database_connection
            # LAZYLOADED # - @system.status
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    bootcamp.exceptionlistener:
        class: Netgusto\BootCampBundle\EventListener\InitializationExceptionListener
        scope: request
        arguments:
            # Event listener are not lazyloaded, so need to inject service container to still lazyload @initialization.controller
            - @service_container
            - @database_connection
            - @environment
            - @request
            # LAZYLOADED # - @initialization.controller
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    scalar.interpreter:
        class: Netgusto\BootCampBundle\Services\ScalarInterpreterService

    environment:
        class: Netgusto\BootCampBundle\Services\Context\EnvironmentService
        arguments:
            - %environment_resolved%
            - @scalar.interpreter
            - %kernel.root_dir%

    system.status:
        class: Netgusto\BootCampBundle\Services\Context\SystemStatusService
        arguments:
            - @doctrine.orm.entity_manager

    initialization.controller:
        class: Netgusto\BootCampBundle\Controller\InitializationController
        lazy: true
        arguments:
            # To disable the profiler bar if defined
            - @service_container
            - @twig
            - @environment
            - @router
            - @form.factory
            - @doctrine.orm.entity_manager
            - %appversion%
            - @security.encoder_factory
            - @system.status