services:

    bootcamp.init.autoroute:
        class: Netgusto\AutorouteBundle\Routing\AutorouteProvider
        arguments:
            - @='@NetgustoBootCampBundle/Resources/config/routes/init.yml'
        tags:
            - { name: autoroute.provider, prefix: '/_init'}

    bootcamp.systemhealth:
        class: Netgusto\BootCampBundle\EventListener\SystemHealthCheckerListener
        arguments:
            # Event listener are not lazyloaded, so need to inject service container to still lazyload @system.status
            - @service_container
            - @environment
            - @database_connection
            # LAZYLOADED # - @system.status
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    bootcamp.exceptionlistener:
        class: Netgusto\BootCampBundle\EventListener\InitializationExceptionListener
        scope: request
        arguments:
            # Event listener are not lazyloaded, so need to inject service container to still lazyload @initialization.controller
            - @service_container
            - @environment
            - @request
            # LAZYLOADED # - @database_connection
            # LAZYLOADED # - @initialization.controller
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    bootcamp.default_user_init_handler:
        class: Netgusto\BootCampBundle\Services\UserInitHandler\DefaultUserInitHandler
        arguments:
            - @doctrine.orm.entity_manager
            - @security.encoder_factory
            - %bootcamp.userinit.class%
            - %bootcamp.userinit.roles%
            - %bootcamp.userinit.mapping.username%
            - %bootcamp.userinit.mapping.roles%
            - %bootcamp.userinit.mapping.password%
            - %bootcamp.userinit.mapping.salt%

    bootcamp.default_config_init_handler:
        class: Netgusto\BootCampBundle\Services\ConfigInitHandler\DefaultConfigInitHandler
        arguments:
            - @doctrine.orm.entity_manager
            - %bootcamp.initconfig.file%

    scalar.interpreter:
        class: Netgusto\BootCampBundle\Services\ScalarInterpreterService

    environment:
        class: Netgusto\BootCampBundle\Services\Context\EnvironmentService
        arguments:
            - %environment_resolved%
            - @scalar.interpreter
            - %kernel.root_dir%

    system.status:
        class: Netgusto\BootCampBundle\Services\Context\SystemStatusService
        arguments:
            - @doctrine.orm.entity_manager

    twig.bootcampextension:
        class: Netgusto\BootCampBundle\Twig\BootCampExtension
        arguments:
            # Inject service container to lazyload dependencies
            - @service_container
        tags:
            - { name: twig.extension }

    config.loader.dbbacked:
        class: Netgusto\BootCampBundle\Services\Config\Loader\DbBackedConfigLoaderService
        arguments:
            - @doctrine.orm.entity_manager
            - Netgusto\BootCampBundle\Entity\ConfigContainer

    bootcamp.config.main:
        class: Netgusto\BootCampBundle\Services\Config\DefaultConfigService
        arguments:
            - @doctrine.orm.entity_manager
        calls:
            - [ "initialize", [ "@=service('config.loader.dbbacked').load('main')" ] ]

    # config.main is aliased in Netgusto\BootCampBundle\DependencyInjection\NetgustoBootCampExtension (cannot use %parameter% in alias)
    #config.main:
    #    alias: %bootcamp.config.service%

    initialization.controller:
        class: Netgusto\BootCampBundle\Controller\InitializationController
        lazy: true
        arguments:
            # To disable the profiler bar if defined
            - @service_container
            - @twig
            - @environment
            - @router
            - @form.factory
            - @security.encoder_factory
            - @system.status

            # LAZYLOADED # - @doctrine.orm.entity_manager